### ISSUE TITLE
Alternative method for converting a vectorized/png image into coord

### ISSUE THREAD

**Issue by tiagobrc** [pachterlab/picasso#1]
Congratulations on making this thought-provoking tool!

I am trying to use it and got stuck on creating my coordinate file. One of the notebooks uses Mathematica. Is there an alternative method? I am trying to download a free trial of Matematica to try the code anyways.

Thanks again.

**Comment by tarachari3** [comment]
Yes, you can definitely do this is other languages. All that the Mathematica code is doing is taking a black and white image, and finding the coordinates of the black outline.

In python, you can convert an image to black and white with PIL as described [here ](https://stackoverflow.com/questions/9506841/using-python-pil-to-turn-a-rgb-image-into-a-pure-black-and-white-image/50090612#50090612) and then select the coordinates of the non-white points (the shape outline) as described [here](https://stackoverflow.com/questions/44068654/finding-all-the-x-and-y-coordinates-of-an-image-in-python-opencv/50277781#50277781).  This should then produce a set of x,y coordinates to use as input.

**Comment by tiagobrc** [comment]
Thank you for the fast response. This is very helpful. I will try.
